export const changelog = {
  "0.2.21": [
    "Added support for DO_NOT_TRACK environment variable to disable analytics",
  ],
  "0.2.20": [
    "Added header when url is empty",
    "Added fade in on meta info",
    "Added InputSuggestions component to show suggestions for input.",
    "Added the ability to see recent searches.",
    "Added facebook preview, light and dark theme.",
    "Added google light and dark theme",
    "Added twitter dim and dark theme",
    "Added appear animation on each preview",
    "Added discord light mode",
    "Added reset and retry button",
    "Added changelog",
    "Improved the UI of the input button and overall UI",
    "Switched to JetBrains Mono font for mono text",
    "Refactor component.css and tabs",
    "Tweaked the colors of the UI",
    "Fixed input form not capturing query state after changed. It is now rendered in the client.",
    "Fixed analytics not sending proper version number.",
    "Fixed preview frame showing under the preview theme toggle",
    "Fixed twitter preview overflow issue",
    "Fixed typo",
  ],
  "0.2.12": [
    "Fixed favicon summary not recognizing invalid type",
    "Removed some boilerplate images",
  ],
  "0.2.11": [
    "Added discord theme color quirky feature",
    "Added dark mode",
    "Added theme switcher",
    "Added twitter font",
    "Added '<head>' tab to the summary to see raw html",
    "Fixed version not appearing in the site",
    "Fixed error color on dark mdoe",
    "Fixed button inside button error",
    "Fixed svg favicon not being displayed correctly",
    "Fixed url in Icons tab not being displayed as a link",
    "Fixed centered field key",
    "Improve AppImage: use native value before using proxy URL",
    "Improve image proxy and support for SVG favicons",
    "Improve footer",
    "Improve discord link preview",
    "Refactor favicon code",
  ],
  "0.2.10": [
    "Improved analytics",
  ],
  "0.2.9": [
    "Added analytics when check form is submitted",
    "Fixed overflow issue",
    "Save tab state into URL",
    "Improve animations",
    "Added option to disable analytics --no-analytics",
  ],
  "0.2.6": [
    "Removed experimental node syntax (with) for better compatibility",
  ],
}